/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "cam_hex_canary.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CAM_HEX_camera_data_frame, CAM_HEX_camera_data_frame, AUTO)


PB_BIND(CAM_HEX_cmd_frame, CAM_HEX_cmd_frame, AUTO)


PB_BIND(CAM_HEX_ack_frame, CAM_HEX_ack_frame, AUTO)





