/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "ant_canary.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Ant_tracking_data_frame, Ant_tracking_data_frame, AUTO)


PB_BIND(Ant_IR_data_frame, Ant_IR_data_frame, AUTO)


PB_BIND(Ant_cmd_frame, Ant_cmd_frame, AUTO)


PB_BIND(Ant_ack_frame, Ant_ack_frame, AUTO)





