/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_ANT_CANARY_PB_H_INCLUDED
#define PB_ANT_CANARY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _CMD_RECV {
    CMD_RECV_START = 0,
    CMD_RECV_FORWARD = 1,
    CMD_RECV_BACKWARD = 2,
    CMD_RECV_TURN_L = 3,
    CMD_RECV_TURN_R = 4,
    CMD_RECV_PING = 5,
    CMD_RECV_TAKEIR = 6,
    CMD_RECV_INVAID = 7
} CMD_RECV;

typedef enum _ACK2SEND {
    ACK2SEND_ACK = 0,
    ACK2SEND_NCK = 1
} ACK2SEND;

/* Struct definitions */
typedef struct _Ant_tracking_data_frame {
    int32_t ID;
    int32_t time_stamp;
    int32_t seq_num;
    int32_t battery_v;
    int32_t encoder_cnt;
    float gyro_data;
    int32_t crc;
} Ant_tracking_data_frame;

typedef struct _Ant_IR_data_frame {
    int32_t ID;
    int32_t seq_num;
    float IR_data_1;
    float IR_data_2;
    float IR_data_3;
    float IR_data_4;
    float IR_data_5;
    float IR_data_6;
    float IR_data_7;
    float IR_data_8;
    float IR_data_9;
    float IR_data_10;
    float IR_data_11;
    float IR_data_12;
    float IR_data_13;
    float IR_data_14;
    float IR_data_15;
    float IR_data_16;
    float IR_data_17;
    float IR_data_18;
    float IR_data_19;
    float IR_data_20;
    float IR_data_21;
    float IR_data_22;
    float IR_data_23;
    float IR_data_24;
    int32_t crc;
} Ant_IR_data_frame;

typedef struct _Ant_cmd_frame {
    CMD_RECV cmd_recv;
    int32_t dis_ang;
    int32_t crc;
} Ant_cmd_frame;

typedef struct _Ant_ack_frame {
    int32_t ID;
    CMD_RECV cmd_recv;
    ACK2SEND ack2send;
    int32_t crc;
} Ant_ack_frame;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _CMD_RECV_MIN CMD_RECV_START
#define _CMD_RECV_MAX CMD_RECV_INVAID
#define _CMD_RECV_ARRAYSIZE ((CMD_RECV)(CMD_RECV_INVAID+1))

#define _ACK2SEND_MIN ACK2SEND_ACK
#define _ACK2SEND_MAX ACK2SEND_NCK
#define _ACK2SEND_ARRAYSIZE ((ACK2SEND)(ACK2SEND_NCK+1))



#define Ant_cmd_frame_cmd_recv_ENUMTYPE CMD_RECV

#define Ant_ack_frame_cmd_recv_ENUMTYPE CMD_RECV
#define Ant_ack_frame_ack2send_ENUMTYPE ACK2SEND


/* Initializer values for message structs */
#define Ant_tracking_data_frame_init_default     {0, 0, 0, 0, 0, 0, 0}
#define Ant_IR_data_frame_init_default           {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define Ant_cmd_frame_init_default               {_CMD_RECV_MIN, 0, 0}
#define Ant_ack_frame_init_default               {0, _CMD_RECV_MIN, _ACK2SEND_MIN, 0}
#define Ant_tracking_data_frame_init_zero        {0, 0, 0, 0, 0, 0, 0}
#define Ant_IR_data_frame_init_zero              {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define Ant_cmd_frame_init_zero                  {_CMD_RECV_MIN, 0, 0}
#define Ant_ack_frame_init_zero                  {0, _CMD_RECV_MIN, _ACK2SEND_MIN, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Ant_tracking_data_frame_ID_tag           1
#define Ant_tracking_data_frame_time_stamp_tag   2
#define Ant_tracking_data_frame_seq_num_tag      3
#define Ant_tracking_data_frame_battery_v_tag    4
#define Ant_tracking_data_frame_encoder_cnt_tag  5
#define Ant_tracking_data_frame_gyro_data_tag    6
#define Ant_tracking_data_frame_crc_tag          7
#define Ant_IR_data_frame_ID_tag                 1
#define Ant_IR_data_frame_seq_num_tag            2
#define Ant_IR_data_frame_IR_data_1_tag          3
#define Ant_IR_data_frame_IR_data_2_tag          4
#define Ant_IR_data_frame_IR_data_3_tag          5
#define Ant_IR_data_frame_IR_data_4_tag          6
#define Ant_IR_data_frame_IR_data_5_tag          7
#define Ant_IR_data_frame_IR_data_6_tag          8
#define Ant_IR_data_frame_IR_data_7_tag          9
#define Ant_IR_data_frame_IR_data_8_tag          10
#define Ant_IR_data_frame_IR_data_9_tag          11
#define Ant_IR_data_frame_IR_data_10_tag         12
#define Ant_IR_data_frame_IR_data_11_tag         13
#define Ant_IR_data_frame_IR_data_12_tag         14
#define Ant_IR_data_frame_IR_data_13_tag         15
#define Ant_IR_data_frame_IR_data_14_tag         16
#define Ant_IR_data_frame_IR_data_15_tag         17
#define Ant_IR_data_frame_IR_data_16_tag         18
#define Ant_IR_data_frame_IR_data_17_tag         19
#define Ant_IR_data_frame_IR_data_18_tag         20
#define Ant_IR_data_frame_IR_data_19_tag         21
#define Ant_IR_data_frame_IR_data_20_tag         22
#define Ant_IR_data_frame_IR_data_21_tag         23
#define Ant_IR_data_frame_IR_data_22_tag         24
#define Ant_IR_data_frame_IR_data_23_tag         25
#define Ant_IR_data_frame_IR_data_24_tag         26
#define Ant_IR_data_frame_crc_tag                27
#define Ant_cmd_frame_cmd_recv_tag               1
#define Ant_cmd_frame_dis_ang_tag                2
#define Ant_cmd_frame_crc_tag                    3
#define Ant_ack_frame_ID_tag                     1
#define Ant_ack_frame_cmd_recv_tag               2
#define Ant_ack_frame_ack2send_tag               3
#define Ant_ack_frame_crc_tag                    4

/* Struct field encoding specification for nanopb */
#define Ant_tracking_data_frame_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    ID,                1) \
X(a, STATIC,   SINGULAR, INT32,    time_stamp,        2) \
X(a, STATIC,   SINGULAR, INT32,    seq_num,           3) \
X(a, STATIC,   SINGULAR, INT32,    battery_v,         4) \
X(a, STATIC,   SINGULAR, INT32,    encoder_cnt,       5) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_data,         6) \
X(a, STATIC,   SINGULAR, INT32,    crc,               7)
#define Ant_tracking_data_frame_CALLBACK NULL
#define Ant_tracking_data_frame_DEFAULT NULL

#define Ant_IR_data_frame_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    ID,                1) \
X(a, STATIC,   SINGULAR, INT32,    seq_num,           2) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_1,         3) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_2,         4) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_3,         5) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_4,         6) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_5,         7) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_6,         8) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_7,         9) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_8,        10) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_9,        11) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_10,       12) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_11,       13) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_12,       14) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_13,       15) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_14,       16) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_15,       17) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_16,       18) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_17,       19) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_18,       20) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_19,       21) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_20,       22) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_21,       23) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_22,       24) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_23,       25) \
X(a, STATIC,   SINGULAR, FLOAT,    IR_data_24,       26) \
X(a, STATIC,   SINGULAR, INT32,    crc,              27)
#define Ant_IR_data_frame_CALLBACK NULL
#define Ant_IR_data_frame_DEFAULT NULL

#define Ant_cmd_frame_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    cmd_recv,          1) \
X(a, STATIC,   SINGULAR, INT32,    dis_ang,           2) \
X(a, STATIC,   SINGULAR, INT32,    crc,               3)
#define Ant_cmd_frame_CALLBACK NULL
#define Ant_cmd_frame_DEFAULT NULL

#define Ant_ack_frame_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    ID,                1) \
X(a, STATIC,   SINGULAR, UENUM,    cmd_recv,          2) \
X(a, STATIC,   SINGULAR, UENUM,    ack2send,          3) \
X(a, STATIC,   SINGULAR, INT32,    crc,               4)
#define Ant_ack_frame_CALLBACK NULL
#define Ant_ack_frame_DEFAULT NULL

extern const pb_msgdesc_t Ant_tracking_data_frame_msg;
extern const pb_msgdesc_t Ant_IR_data_frame_msg;
extern const pb_msgdesc_t Ant_cmd_frame_msg;
extern const pb_msgdesc_t Ant_ack_frame_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Ant_tracking_data_frame_fields &Ant_tracking_data_frame_msg
#define Ant_IR_data_frame_fields &Ant_IR_data_frame_msg
#define Ant_cmd_frame_fields &Ant_cmd_frame_msg
#define Ant_ack_frame_fields &Ant_ack_frame_msg

/* Maximum encoded size of messages (where known) */
#define ANT_CANARY_PB_H_MAX_SIZE                 Ant_IR_data_frame_size
#define Ant_IR_data_frame_size                   165
#define Ant_ack_frame_size                       26
#define Ant_cmd_frame_size                       24
#define Ant_tracking_data_frame_size             71

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
