/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "env_comm.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Env_data_frame, Env_data_frame, AUTO)


PB_BIND(Env_cmd_frame, Env_cmd_frame, AUTO)


PB_BIND(Env_ack_frame, Env_ack_frame, AUTO)





